---
title: "Lab 6 Notes"
author: "Tessa McDonnel"
date: "7/19/2017"
output: html_document
---


# Objectives
- How to do a 2-sample t test 
- How to execute a paired t-test for mean difference
- How to use ANOVA when more than 2 means

# Statistical Concepts
- using a 2 sample t-test to find significant difference between groups in a categorical variable
- If a confidence interval contains 0, the test is not significant (Possible there is **no** difference between groups)
- difference between paired and 2-sample t-test

# R Concepts/Syntax
- installing "HSAUR" package for data sets
- t.test for a two sample t-test
- t.test for a paired t-test
- aov() function for comparing more than 2 means
- TukeyHSD

# DataCamp Course Outline
- Accessing data with HSAUR
- Assumptions for 2-sample t (normallity or number > 30, independent obs)
- How to use t.test() for 2-sample
- Assumptions for paired t-test (independence of obs, )
- Using the paired = TRUE option to perform paired test


# Questions
- will you always specify var.equal = FALSE?
- schooldays data set in HSAUR not normal but n >30 is that okay?
- do you want them to type library(mosaic) themselves?
<<<<<<< HEAD
- Im having trouble figuring out how to do the 'not equal' sign in the plots and still keeping mu as the symbol
- charlatan

=======
- I'm having trouble figuring out how to do the 'not equal' sign in the plots and still keeping mu as the symbol
- Can I use Anorexia data from MASS package for all of lab 6?
>>>>>>> 0a7f9ad9a90bbdb555c4802fffec015a884bfb9f


# Notes
- look into TISE for the article 
- look into charatan
- make them type library (mosiac)
- add questions about if the conditions were satisfied
